apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-dotnet-deploy
  labels:
    app: my-dotnet
spec:
  replicas: 6
  selector:
    matchLabels:
      app: my-dotnet
  template:
    metadata:
      labels:
        app: my-dotnet
    spec:
      containers:
        - name: core-dotnet-cont
          image: ajjurathod1998/dotnet1-core:v1.0.0
          ports:
            - containerPort: 5000
          env:
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:5000"  
